version: 3

tasks:
  start:
    desc: Start app
    deps:
      - :missing-configuration
    cmds:
      - task: :docker:compose:up
      - task: :symfony:server:start

  stop:
    desc: Stop app
    deps:
      - :missing-configuration
    cmds:
      - task: :docker:compose:stop