name: ${PROJECT_NAME}

include:
  - compose.project.yaml

services:
  php:
    image: ${PROJECT_NAME}-php:prod
    build:
      context: ${PROJECT_DIR}/${PHP_APP_DIR}
      dockerfile: ${PROJECT_DIR}/environment/docker/dockerfile/php/prod/Dockerfile
    env_file:
      - .env.compose
    volumes:
      - jwt_keys:/app/config/jwt
    working_dir: /app

  postgres:
    image: postgres
    env_file:
      - .env.compose
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${PROJECT_DIR}/.data/postgres:/var/lib/postgresql/data

  node:
    image: ${PROJECT_NAME}-node:prod
    build:
      context: ${PROJECT_DIR}/${NODE_APP_DIR}
      dockerfile: ${PROJECT_DIR}/environment/docker/dockerfile/node/prod/Dockerfile
    env_file:
      - .env.compose
    working_dir: /app

volumes:
  jwt_keys: